### ISSUE TITLE
@jgoz/esbuild-plugin-livereload error loading `livereload-event-source.js` over network

### ISSUE THREAD

**Issue by KurtPreston** [jgoz/esbuild-plugins#114]
Hello again! I've been trying to get your livereload plugin working, but am receiving the error `net::ERR_CONNECTION_REFUSED` when the page tries to load `http://$HOST:$LIVERELOADPORT/livereload-event-source.js`.

When I am writing code, I am SSH'd into my dev machine, then accessing the web page over the network. I assume that the livereload server being stood up is refusing external connections? Is there a way to disable that?

I can access `livereload-event-source.js` when I `curl` the same endpoint while SSH'd into my dev box. I have tried changing the `host` parameter to the hostname of my dev server. This does change the livereload URL, but it can still only be accessed locally.

**Comment by jgoz** [comment]
Hey @KurtPreston, I commented this on your PR (thanks again for the submission), but I think you can achieve this by passing `host: '0.0.0.0'` directly to the plugin options: https://github.com/jgoz/esbuild-plugins/tree/master/packages/esbuild-plugin-livereload#function-livereloadpluginoptions-livereloadpluginoptions-plugin

Can you please give that a try and let me know if it works?

**Comment by KurtPreston** [comment]
@jgoz I tried that. The issue is that I'm developing on computer A over SSH, but accessing my web page on computer B.

If I set the `host` to `0.0.0.0`, then the live reload sever on computer A will successfully accept connections from external addresses, however, when I access the web page on computer B, I get an error loading the `livereload-event-source.js` script, since it attempts to fetch it from `0.0.0.0`, which does not point back to computer A.

I have also tried setting the `host` parameter to the `hostname` of computer A. Unfortunately, this does not seem to work. I can access `http://COMPUTER_A:PORT/livereload-event-source.js` from computer A, but I get `ERR_CONNECTION_REFUSED` accessing it from computer B.

The only way I've managed to get it working is to tell the server to host on `0.0.0.0`, but to leave the `host` as the hostname of computer A.

**Comment by jgoz** [comment]
I see, thanks for the explanation, I wasn't getting the full picture.

I wonder if this alternate approach would work:
- Accept `urlHostname` parameter that defaults to the value of `host`
- Set `host: '0.0.0.0'`
- Set `urlHostname: '<hostname of computer A>'`

Maybe this would be a more flexible way to allow for this use case and potentially others?

**Comment by KurtPreston** [comment]
I think that would work, good idea!

**Comment by jgoz** [comment]
@KurtPreston The `urlHostname` option is now available in `@jgoz/esbuild-plugin-livereload@2.1.0`. Could you please try it out and reopen this issue if you run into any problems?
