### ISSUE TITLE
Type checking failures pass CI checks

### ISSUE THREAD

**Issue by zfoster** [jgoz/esbuild-plugins#130]
Hi @jgoz thanks for the awesome plugin. I've added typechecking as a build step in CI, it seems even when the typechecking fails the build passes the CI check and you get a green build. I've tried a couple things like changing the shell to bash, but figure I'd post an issue and see if you have any obvious insights I'm missing.

Thanks!

**Comment by zfoster** [comment]
Was able to resolve this, unrelated to the plugin as expected

**Comment by jgoz** [comment]
👍 Glad to hear it. Would you mind posting what the problem was, if you have time? Just in case someone else encounters this.

I looked through the code again and saw that it was setting `process.exitCode` on failure, so I thought it might be related to how esbuild was being invoked in your case.

**Comment by zfoster** [comment]
my custom build script was calling `.catch` on the errors 🙈
