### ISSUE TITLE
The 'esbuild-plugin-html' plugin reads the template file only once during initialization

### ISSUE THREAD

**Issue by jngross95** [jgoz/esbuild-plugins#79]
The plugin '@jgoz/esbuild-plugin-html' reads the template file only once during plugin initialization. If the file changes, outdated data is processed in the OnEnd. I'm using esbuild in watch mode. It would be good if the template is always read from the disk in the OnEnd

**Comment by jgoz** [comment]
Better late than never 😅 

I applied your suggestion in `@jgoz/esbuild-plugin-html@1.0.7`. Please give it a try!
