### ISSUE TITLE
Don't console.error anything if there are no errors/warnings to report

### ISSUE THREAD

**Issue by lesha-co** [jgoz/esbuild-plugins#84]
I just don't like empty lines in output. 
Can you please check if `msg.output` is empty and skip console.error call if it is?

https://github.com/jgoz/esbuild-plugins/blob/b330086575cb337b1f4b33efe70badfecc9f04e8/packages/esbuild-plugin-typecheck/src/typecheck-runner.ts#L91

**Comment by jgoz** [comment]
Hi there, I started checking for empty strings in `@jgoz/esbuild-plugin-typecheck@3.1.2`. Please give it a try!
