### ISSUE TITLE
Error overlay does not work

### ISSUE THREAD

**Issue by DinerIsmail** [jgoz/esbuild-plugins#94]
The error overlay does not seem to appear, so far I haven't seen it any circumstance even when esbuild encounters an error. Is there any configuration that needs to be set for it to work?
I found that there's [this package](https://www.npmjs.com/package/@jgoz/esbuild-overlay), but it seems that's only intended for using within `esbuild-plugin-livereload`.

Do you think there's something I'm doing wrong or could there be a bug that causes the error overlay not to appear?

**Comment by jgoz** [comment]
Closing for now until more details are provided. Feel free to reopen.
